filter:
    excluded_paths:
        - "**/__tests__/"
        - "*.test.js"
        - "*.min.js"
build:
    environment:
        node: v9.3.0
    tests:
        override:
            -
                command: 'docker-compose up -d mongodb && npm run coverage && docker-compose-down'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
